### ISSUE TITLE
win10下无法运行

### ISSUE THREAD

**Issue by jielansudo** [mark0smith/Kunlun-M-GUI#1]
已经讲exe文件放到kunlun文件同目录下，也无法运行

**Comment by mark0smith** [comment]
1. 请问你有按照KunLun-M的说明进行安装、初始化设置吗？
https://github.com/LoRexxar/Kunlun-M#%E5%AE%89%E8%A3%85

2. 不知道你能不能提供下你的db目录下的数据库文件给我进行分析看看。
